/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "Txrequest.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TxRequest, TxRequest, 4)


PB_BIND(Payload, Payload, 4)


PB_BIND(KeyValuePair, KeyValuePair, AUTO)


PB_BIND(Limit, Limit, AUTO)


PB_BIND(EndorsementEntry, EndorsementEntry, 2)


PB_BIND(Member, Member, AUTO)



